# Generated by Django 3.1.7 on 2021-02-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalmanagement', '0013_auto_20210227_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(),
        ),
    ]
